apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpledjangorestapi
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simpledjangorestapi
  template:
    metadata:
      labels:
        app: simpledjangorestapi
    spec:
      containers:
      - name: simpledjangorestapi
        image: simpledjangorestapi:v1
---
apiVersion: v1
kind: Service
metadata:
  name: simpledjangorestapi-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: simpledjangorestapi
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30001


